version: "3"

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  jenkins_home: