FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
 && apt-get install -y \
  ca-certificates \
  curl \
  gnupg \
  lsb-release \
  curl \
  sudo \
 && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
 && echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null \
 && apt-get update \
 && apt-get install  -y \
  docker-ce \
  docker-ce-cli \
  containerd.io \
 && usermod -a -G docker jenkins \
 && groupadd -g 992 docker2 \
 && usermod -a -G docker2 jenkins

USER jenkins