pipeline {
    agent {
        docker { image 'node:16.13.1-alpine' }
    }
    stages {
        stage('Docker install') {
            agent {
                label 'master'
            }
            steps {
                sh '''
                    docker ps
                '''
            }
        }
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}